context.spa-libs = {
    audio.convert.* = audioconvert/libspa-audioconvert
    support.*       = support/libspa-support
}
context.modules = [
    { name = libpipewire-module-rt flags = [ ifexists nofail ] }
    { name = libpipewire-module-protocol-native }
    { name = libpipewire-module-client-node }
    { name = libpipewire-module-adapter }
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Test EQ"
            media.name       = "Test EQ"
            filter.graph = {
                nodes = [
                    {
                        type = builtin
                        name = eq_band_1
                        label = bq_peaking
                        control = { "Freq" = 100.0 "Q" = 1.0 "Gain" = 5.0 }
                    }
                    {
                        type = builtin
                        name = eq_band_2
                        label = bq_peaking
                        control = { "Freq" = 200.0 "Q" = 1.0 "Gain" = -5.0 }
                    }
                ]
                links = [
                    { output = "eq_band_1:Out" input = "eq_band_2:In" }
                ]
            }
            audio.channels = 2
            audio.position = [ FL FR ]
            capture.props = {
                node.name = "effect_input.eq"
                media.class = Audio/Sink
            }
            playback.props = {
                node.name = "effect_output.eq"
                node.target = "alsa_output.pci-0000_c4_00.6.HiFi__Speaker__sink"
            }
        }
    }
]
