// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

List<Point> calculateBiquadResponse({required List<ActiveFilter> filters}) =>
    RustLib.instance.api.crateApiSimpleCalculateBiquadResponse(
      filters: filters,
    );

class ActiveFilter {
  final FilterType filterType;
  final double freq;
  final double gain;
  final double q;

  const ActiveFilter({
    required this.filterType,
    required this.freq,
    required this.gain,
    required this.q,
  });

  @override
  int get hashCode =>
      filterType.hashCode ^ freq.hashCode ^ gain.hashCode ^ q.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveFilter &&
          runtimeType == other.runtimeType &&
          filterType == other.filterType &&
          freq == other.freq &&
          gain == other.gain &&
          q == other.q;
}

enum FilterType { peaking, lowShelf, highShelf }

class Point {
  final double x;
  final double y;

  const Point({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
