// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `interpolate_points`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

List<Point> calculateBiquadResponse({required List<ActiveFilter> filters}) =>
    RustLib.instance.api.crateApiSimpleCalculateBiquadResponse(
      filters: filters,
    );

List<HeadphoneModel> getHeadphoneModels({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleGetHeadphoneModels(dbPath: dbPath);

List<String> getTargets({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleGetTargets(dbPath: dbPath);

Future<void> syncDatabase({required String dbPath}) =>
    RustLib.instance.api.crateApiSimpleSyncDatabase(dbPath: dbPath);

List<Point> getTargetCurve({
  required String dbPath,
  required String targetName,
}) => RustLib.instance.api.crateApiSimpleGetTargetCurve(
  dbPath: dbPath,
  targetName: targetName,
);

DualMeasurementResult parseCsvMeasurement({required String csvContent}) =>
    RustLib.instance.api.crateApiSimpleParseCsvMeasurement(
      csvContent: csvContent,
    );

DualMeasurementResult getDualHeadphoneCurve({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleGetDualHeadphoneCurve(
      filePath: filePath,
    );

List<Point> getHeadphoneCurve({required String filePath}) =>
    RustLib.instance.api.crateApiSimpleGetHeadphoneCurve(filePath: filePath);

DualMeasurementResult simulateDualChannelImbalance({
  required List<Point> baseCurve,
  required int seed,
}) => RustLib.instance.api.crateApiSimpleSimulateDualChannelImbalance(
  baseCurve: baseCurve,
  seed: seed,
);

ChannelMatchResult matchRawChannels({
  required List<Point> rawL,
  required List<Point> rawR,
  required BigInt maxBands,
}) => RustLib.instance.api.crateApiSimpleMatchRawChannels(
  rawL: rawL,
  rawR: rawR,
  maxBands: maxBands,
);

List<String> getAudioDevices() =>
    RustLib.instance.api.crateApiSimpleGetAudioDevices();

void applyStereoEqToDevice({
  required String deviceName,
  required List<ActiveFilter> leftFilters,
  required List<ActiveFilter> rightFilters,
}) => RustLib.instance.api.crateApiSimpleApplyStereoEqToDevice(
  deviceName: deviceName,
  leftFilters: leftFilters,
  rightFilters: rightFilters,
);

void applyEqToDevice({
  required String deviceName,
  required List<ActiveFilter> filters,
}) => RustLib.instance.api.crateApiSimpleApplyEqToDevice(
  deviceName: deviceName,
  filters: filters,
);

List<ActiveFilter> generateAutoeq({
  required List<Point> headphone,
  required List<Point> target,
  required BigInt bands,
}) => RustLib.instance.api.crateApiSimpleGenerateAutoeq(
  headphone: headphone,
  target: target,
  bands: bands,
);

List<Point> modifyTarget({
  required List<Point> baseTarget,
  required double tilt,
  required double bass,
  required double treble,
  required double earGain,
}) => RustLib.instance.api.crateApiSimpleModifyTarget(
  baseTarget: baseTarget,
  tilt: tilt,
  bass: bass,
  treble: treble,
  earGain: earGain,
);

class ActiveFilter {
  final FilterType filterType;
  final double freq;
  final double gain;
  final double q;

  const ActiveFilter({
    required this.filterType,
    required this.freq,
    required this.gain,
    required this.q,
  });

  @override
  int get hashCode =>
      filterType.hashCode ^ freq.hashCode ^ gain.hashCode ^ q.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ActiveFilter &&
          runtimeType == other.runtimeType &&
          filterType == other.filterType &&
          freq == other.freq &&
          gain == other.gain &&
          q == other.q;
}

class ChannelMatchResult {
  final List<ActiveFilter> leftFilters;
  final List<ActiveFilter> rightFilters;
  final List<Point> matchedL;
  final List<Point> matchedR;
  final double residualImbalanceDb;

  const ChannelMatchResult({
    required this.leftFilters,
    required this.rightFilters,
    required this.matchedL,
    required this.matchedR,
    required this.residualImbalanceDb,
  });

  @override
  int get hashCode =>
      leftFilters.hashCode ^
      rightFilters.hashCode ^
      matchedL.hashCode ^
      matchedR.hashCode ^
      residualImbalanceDb.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChannelMatchResult &&
          runtimeType == other.runtimeType &&
          leftFilters == other.leftFilters &&
          rightFilters == other.rightFilters &&
          matchedL == other.matchedL &&
          matchedR == other.matchedR &&
          residualImbalanceDb == other.residualImbalanceDb;
}

class DualMeasurementResult {
  final bool isDualChannel;
  final List<Point> rawL;
  final List<Point> rawR;
  final List<Point> rawMid;
  final double avgImbalanceDb;
  final double maxImbalanceDb;
  final double maxImbalanceFreq;

  const DualMeasurementResult({
    required this.isDualChannel,
    required this.rawL,
    required this.rawR,
    required this.rawMid,
    required this.avgImbalanceDb,
    required this.maxImbalanceDb,
    required this.maxImbalanceFreq,
  });

  @override
  int get hashCode =>
      isDualChannel.hashCode ^
      rawL.hashCode ^
      rawR.hashCode ^
      rawMid.hashCode ^
      avgImbalanceDb.hashCode ^
      maxImbalanceDb.hashCode ^
      maxImbalanceFreq.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DualMeasurementResult &&
          runtimeType == other.runtimeType &&
          isDualChannel == other.isDualChannel &&
          rawL == other.rawL &&
          rawR == other.rawR &&
          rawMid == other.rawMid &&
          avgImbalanceDb == other.avgImbalanceDb &&
          maxImbalanceDb == other.maxImbalanceDb &&
          maxImbalanceFreq == other.maxImbalanceFreq;
}

enum FilterType { peaking, lowShelf, highShelf }

class HeadphoneModel {
  final String brand;
  final String model;
  final String? formFactor;
  final String? rig;
  final String? filePath;

  const HeadphoneModel({
    required this.brand,
    required this.model,
    this.formFactor,
    this.rig,
    this.filePath,
  });

  @override
  int get hashCode =>
      brand.hashCode ^
      model.hashCode ^
      formFactor.hashCode ^
      rig.hashCode ^
      filePath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeadphoneModel &&
          runtimeType == other.runtimeType &&
          brand == other.brand &&
          model == other.model &&
          formFactor == other.formFactor &&
          rig == other.rig &&
          filePath == other.filePath;
}

class Point {
  final double x;
  final double y;

  const Point({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
