// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'dsp/crossfeed.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  ActiveFilter dco_decode_active_filter(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChannelMatchResult dco_decode_channel_match_result(dynamic raw);

  @protected
  CrossfeedCoefficients dco_decode_crossfeed_coefficients(dynamic raw);

  @protected
  CrossfeedConfig dco_decode_crossfeed_config(dynamic raw);

  @protected
  CrossfeedPresetMode dco_decode_crossfeed_preset_mode(dynamic raw);

  @protected
  DualMeasurementResult dco_decode_dual_measurement_result(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  FilterType dco_decode_filter_type(dynamic raw);

  @protected
  HeadphoneModel dco_decode_headphone_model(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ActiveFilter> dco_decode_list_active_filter(dynamic raw);

  @protected
  List<HeadphoneModel> dco_decode_list_headphone_model(dynamic raw);

  @protected
  List<Point> dco_decode_list_point(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<UserPresetModel> dco_decode_list_user_preset_model(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  Point dco_decode_point(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  UserPresetModel dco_decode_user_preset_model(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  ActiveFilter sse_decode_active_filter(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChannelMatchResult sse_decode_channel_match_result(
    SseDeserializer deserializer,
  );

  @protected
  CrossfeedCoefficients sse_decode_crossfeed_coefficients(
    SseDeserializer deserializer,
  );

  @protected
  CrossfeedConfig sse_decode_crossfeed_config(SseDeserializer deserializer);

  @protected
  CrossfeedPresetMode sse_decode_crossfeed_preset_mode(
    SseDeserializer deserializer,
  );

  @protected
  DualMeasurementResult sse_decode_dual_measurement_result(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  FilterType sse_decode_filter_type(SseDeserializer deserializer);

  @protected
  HeadphoneModel sse_decode_headphone_model(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ActiveFilter> sse_decode_list_active_filter(
    SseDeserializer deserializer,
  );

  @protected
  List<HeadphoneModel> sse_decode_list_headphone_model(
    SseDeserializer deserializer,
  );

  @protected
  List<Point> sse_decode_list_point(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<UserPresetModel> sse_decode_list_user_preset_model(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  Point sse_decode_point(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  UserPresetModel sse_decode_user_preset_model(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_active_filter(ActiveFilter self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_channel_match_result(
    ChannelMatchResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crossfeed_coefficients(
    CrossfeedCoefficients self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crossfeed_config(
    CrossfeedConfig self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_crossfeed_preset_mode(
    CrossfeedPresetMode self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dual_measurement_result(
    DualMeasurementResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_filter_type(FilterType self, SseSerializer serializer);

  @protected
  void sse_encode_headphone_model(
    HeadphoneModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_active_filter(
    List<ActiveFilter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_headphone_model(
    List<HeadphoneModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_point(List<Point> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_user_preset_model(
    List<UserPresetModel> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_point(Point self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_user_preset_model(
    UserPresetModel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
