// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dsp/crossfeed.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -68536718;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_core',
        ioDirectory: '../rust_core/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  CrossfeedCoefficients crateApiSimpleApplyCrossfeedCoefficients({
    required double sampleRate,
    required double fCut,
    required double feedDb,
  });

  void crateApiSimpleApplyEqToDevice({
    required String deviceName,
    required List<ActiveFilter> filters,
  });

  void crateApiSimpleApplyStereoEqToDevice({
    required String deviceName,
    required List<ActiveFilter> leftFilters,
    required List<ActiveFilter> rightFilters,
  });

  List<Point> crateApiSimpleCalculateBiquadResponse({
    required List<ActiveFilter> filters,
  });

  void crateApiSimpleDeleteUserPreset({
    required String dbPath,
    required PlatformInt64 id,
  });

  String crateApiSimpleExportPresetEqualizerApo({
    required List<ActiveFilter> leftFilters,
    required List<ActiveFilter> rightFilters,
    required double preamp,
  });

  String crateApiSimpleExportPresetQudelix({
    required List<ActiveFilter> filters,
    required double preamp,
  });

  String crateApiSimpleExportPresetRoon({
    required List<ActiveFilter> filters,
    required double preamp,
  });

  String crateApiSimpleExportPresetWavelet({
    required List<ActiveFilter> filters,
  });

  List<ActiveFilter> crateApiSimpleGenerateAutoeq({
    required List<Point> headphone,
    required List<Point> target,
    required BigInt bands,
  });

  List<String> crateApiSimpleGetAudioDevices();

  CrossfeedConfig crateApiSimpleGetCrossfeedPreset({
    required CrossfeedPresetMode mode,
  });

  CrossfeedConfig crateApiSimpleGetCrossfeedPresetByName({
    required String modeName,
  });

  DualMeasurementResult crateApiSimpleGetDualHeadphoneCurve({
    required String filePath,
  });

  List<Point> crateApiSimpleGetHeadphoneCurve({required String filePath});

  List<HeadphoneModel> crateApiSimpleGetHeadphoneModels({
    required String dbPath,
  });

  List<Point> crateApiSimpleGetTargetCurve({
    required String dbPath,
    required String targetName,
  });

  List<String> crateApiSimpleGetTargets({required String dbPath});

  List<UserPresetModel> crateApiSimpleGetUserPresets({required String dbPath});

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  ChannelMatchResult crateApiSimpleMatchRawChannels({
    required List<Point> rawL,
    required List<Point> rawR,
    required BigInt maxBands,
  });

  List<Point> crateApiSimpleModifyTarget({
    required List<Point> baseTarget,
    required double tilt,
    required double bass,
    required double treble,
    required double earGain,
  });

  DualMeasurementResult crateApiSimpleParseCsvMeasurement({
    required String csvContent,
  });

  PlatformInt64 crateApiSimpleSaveUserPreset({
    required String dbPath,
    required String name,
    required List<ActiveFilter> filters,
    required double preamp,
    String? headphoneName,
  });

  DualMeasurementResult crateApiSimpleSimulateDualChannelImbalance({
    required List<Point> baseCurve,
    required int seed,
  });

  Future<void> crateApiSimpleSyncDatabase({required String dbPath});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  CrossfeedCoefficients crateApiSimpleApplyCrossfeedCoefficients({
    required double sampleRate,
    required double fCut,
    required double feedDb,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_f_64(sampleRate, serializer);
          sse_encode_f_64(fCut, serializer);
          sse_encode_f_64(feedDb, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_crossfeed_coefficients,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApplyCrossfeedCoefficientsConstMeta,
        argValues: [sampleRate, fCut, feedDb],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApplyCrossfeedCoefficientsConstMeta =>
      const TaskConstMeta(
        debugName: "apply_crossfeed_coefficients",
        argNames: ["sampleRate", "fCut", "feedDb"],
      );

  @override
  void crateApiSimpleApplyEqToDevice({
    required String deviceName,
    required List<ActiveFilter> filters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          sse_encode_list_active_filter(filters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApplyEqToDeviceConstMeta,
        argValues: [deviceName, filters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApplyEqToDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "apply_eq_to_device",
        argNames: ["deviceName", "filters"],
      );

  @override
  void crateApiSimpleApplyStereoEqToDevice({
    required String deviceName,
    required List<ActiveFilter> leftFilters,
    required List<ActiveFilter> rightFilters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(deviceName, serializer);
          sse_encode_list_active_filter(leftFilters, serializer);
          sse_encode_list_active_filter(rightFilters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleApplyStereoEqToDeviceConstMeta,
        argValues: [deviceName, leftFilters, rightFilters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApplyStereoEqToDeviceConstMeta =>
      const TaskConstMeta(
        debugName: "apply_stereo_eq_to_device",
        argNames: ["deviceName", "leftFilters", "rightFilters"],
      );

  @override
  List<Point> crateApiSimpleCalculateBiquadResponse({
    required List<ActiveFilter> filters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_active_filter(filters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_point,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleCalculateBiquadResponseConstMeta,
        argValues: [filters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCalculateBiquadResponseConstMeta =>
      const TaskConstMeta(
        debugName: "calculate_biquad_response",
        argNames: ["filters"],
      );

  @override
  void crateApiSimpleDeleteUserPreset({
    required String dbPath,
    required PlatformInt64 id,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_i_64(id, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDeleteUserPresetConstMeta,
        argValues: [dbPath, id],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDeleteUserPresetConstMeta =>
      const TaskConstMeta(
        debugName: "delete_user_preset",
        argNames: ["dbPath", "id"],
      );

  @override
  String crateApiSimpleExportPresetEqualizerApo({
    required List<ActiveFilter> leftFilters,
    required List<ActiveFilter> rightFilters,
    required double preamp,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_active_filter(leftFilters, serializer);
          sse_encode_list_active_filter(rightFilters, serializer);
          sse_encode_f_32(preamp, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleExportPresetEqualizerApoConstMeta,
        argValues: [leftFilters, rightFilters, preamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportPresetEqualizerApoConstMeta =>
      const TaskConstMeta(
        debugName: "export_preset_equalizer_apo",
        argNames: ["leftFilters", "rightFilters", "preamp"],
      );

  @override
  String crateApiSimpleExportPresetQudelix({
    required List<ActiveFilter> filters,
    required double preamp,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_active_filter(filters, serializer);
          sse_encode_f_32(preamp, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleExportPresetQudelixConstMeta,
        argValues: [filters, preamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportPresetQudelixConstMeta =>
      const TaskConstMeta(
        debugName: "export_preset_qudelix",
        argNames: ["filters", "preamp"],
      );

  @override
  String crateApiSimpleExportPresetRoon({
    required List<ActiveFilter> filters,
    required double preamp,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_active_filter(filters, serializer);
          sse_encode_f_32(preamp, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleExportPresetRoonConstMeta,
        argValues: [filters, preamp],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportPresetRoonConstMeta =>
      const TaskConstMeta(
        debugName: "export_preset_roon",
        argNames: ["filters", "preamp"],
      );

  @override
  String crateApiSimpleExportPresetWavelet({
    required List<ActiveFilter> filters,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_active_filter(filters, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleExportPresetWaveletConstMeta,
        argValues: [filters],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleExportPresetWaveletConstMeta =>
      const TaskConstMeta(
        debugName: "export_preset_wavelet",
        argNames: ["filters"],
      );

  @override
  List<ActiveFilter> crateApiSimpleGenerateAutoeq({
    required List<Point> headphone,
    required List<Point> target,
    required BigInt bands,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_point(headphone, serializer);
          sse_encode_list_point(target, serializer);
          sse_encode_usize(bands, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_active_filter,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGenerateAutoeqConstMeta,
        argValues: [headphone, target, bands],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGenerateAutoeqConstMeta =>
      const TaskConstMeta(
        debugName: "generate_autoeq",
        argNames: ["headphone", "target", "bands"],
      );

  @override
  List<String> crateApiSimpleGetAudioDevices() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetAudioDevicesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetAudioDevicesConstMeta =>
      const TaskConstMeta(debugName: "get_audio_devices", argNames: []);

  @override
  CrossfeedConfig crateApiSimpleGetCrossfeedPreset({
    required CrossfeedPresetMode mode,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_crossfeed_preset_mode(mode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_crossfeed_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetCrossfeedPresetConstMeta,
        argValues: [mode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCrossfeedPresetConstMeta =>
      const TaskConstMeta(
        debugName: "get_crossfeed_preset",
        argNames: ["mode"],
      );

  @override
  CrossfeedConfig crateApiSimpleGetCrossfeedPresetByName({
    required String modeName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(modeName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_crossfeed_config,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetCrossfeedPresetByNameConstMeta,
        argValues: [modeName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetCrossfeedPresetByNameConstMeta =>
      const TaskConstMeta(
        debugName: "get_crossfeed_preset_by_name",
        argNames: ["modeName"],
      );

  @override
  DualMeasurementResult crateApiSimpleGetDualHeadphoneCurve({
    required String filePath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dual_measurement_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetDualHeadphoneCurveConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetDualHeadphoneCurveConstMeta =>
      const TaskConstMeta(
        debugName: "get_dual_headphone_curve",
        argNames: ["filePath"],
      );

  @override
  List<Point> crateApiSimpleGetHeadphoneCurve({required String filePath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(filePath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_point,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetHeadphoneCurveConstMeta,
        argValues: [filePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetHeadphoneCurveConstMeta =>
      const TaskConstMeta(
        debugName: "get_headphone_curve",
        argNames: ["filePath"],
      );

  @override
  List<HeadphoneModel> crateApiSimpleGetHeadphoneModels({
    required String dbPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_headphone_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetHeadphoneModelsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetHeadphoneModelsConstMeta =>
      const TaskConstMeta(
        debugName: "get_headphone_models",
        argNames: ["dbPath"],
      );

  @override
  List<Point> crateApiSimpleGetTargetCurve({
    required String dbPath,
    required String targetName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(targetName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_point,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTargetCurveConstMeta,
        argValues: [dbPath, targetName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTargetCurveConstMeta =>
      const TaskConstMeta(
        debugName: "get_target_curve",
        argNames: ["dbPath", "targetName"],
      );

  @override
  List<String> crateApiSimpleGetTargets({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetTargetsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetTargetsConstMeta =>
      const TaskConstMeta(debugName: "get_targets", argNames: ["dbPath"]);

  @override
  List<UserPresetModel> crateApiSimpleGetUserPresets({required String dbPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_user_preset_model,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGetUserPresetsConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGetUserPresetsConstMeta =>
      const TaskConstMeta(debugName: "get_user_presets", argNames: ["dbPath"]);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 20)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  ChannelMatchResult crateApiSimpleMatchRawChannels({
    required List<Point> rawL,
    required List<Point> rawR,
    required BigInt maxBands,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_point(rawL, serializer);
          sse_encode_list_point(rawR, serializer);
          sse_encode_usize(maxBands, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 22)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_channel_match_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleMatchRawChannelsConstMeta,
        argValues: [rawL, rawR, maxBands],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleMatchRawChannelsConstMeta =>
      const TaskConstMeta(
        debugName: "match_raw_channels",
        argNames: ["rawL", "rawR", "maxBands"],
      );

  @override
  List<Point> crateApiSimpleModifyTarget({
    required List<Point> baseTarget,
    required double tilt,
    required double bass,
    required double treble,
    required double earGain,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_point(baseTarget, serializer);
          sse_encode_f_32(tilt, serializer);
          sse_encode_f_32(bass, serializer);
          sse_encode_f_32(treble, serializer);
          sse_encode_f_32(earGain, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_point,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleModifyTargetConstMeta,
        argValues: [baseTarget, tilt, bass, treble, earGain],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleModifyTargetConstMeta => const TaskConstMeta(
    debugName: "modify_target",
    argNames: ["baseTarget", "tilt", "bass", "treble", "earGain"],
  );

  @override
  DualMeasurementResult crateApiSimpleParseCsvMeasurement({
    required String csvContent,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(csvContent, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dual_measurement_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleParseCsvMeasurementConstMeta,
        argValues: [csvContent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleParseCsvMeasurementConstMeta =>
      const TaskConstMeta(
        debugName: "parse_csv_measurement",
        argNames: ["csvContent"],
      );

  @override
  PlatformInt64 crateApiSimpleSaveUserPreset({
    required String dbPath,
    required String name,
    required List<ActiveFilter> filters,
    required double preamp,
    String? headphoneName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          sse_encode_String(name, serializer);
          sse_encode_list_active_filter(filters, serializer);
          sse_encode_f_32(preamp, serializer);
          sse_encode_opt_String(headphoneName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_i_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSaveUserPresetConstMeta,
        argValues: [dbPath, name, filters, preamp, headphoneName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSaveUserPresetConstMeta =>
      const TaskConstMeta(
        debugName: "save_user_preset",
        argNames: ["dbPath", "name", "filters", "preamp", "headphoneName"],
      );

  @override
  DualMeasurementResult crateApiSimpleSimulateDualChannelImbalance({
    required List<Point> baseCurve,
    required int seed,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_point(baseCurve, serializer);
          sse_encode_u_32(seed, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dual_measurement_result,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleSimulateDualChannelImbalanceConstMeta,
        argValues: [baseCurve, seed],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSimulateDualChannelImbalanceConstMeta =>
      const TaskConstMeta(
        debugName: "simulate_dual_channel_imbalance",
        argNames: ["baseCurve", "seed"],
      );

  @override
  Future<void> crateApiSimpleSyncDatabase({required String dbPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(dbPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 27,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSyncDatabaseConstMeta,
        argValues: [dbPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSyncDatabaseConstMeta =>
      const TaskConstMeta(debugName: "sync_database", argNames: ["dbPath"]);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  ActiveFilter dco_decode_active_filter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ActiveFilter(
      filterType: dco_decode_filter_type(arr[0]),
      freq: dco_decode_f_32(arr[1]),
      gain: dco_decode_f_32(arr[2]),
      q: dco_decode_f_32(arr[3]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChannelMatchResult dco_decode_channel_match_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChannelMatchResult(
      leftFilters: dco_decode_list_active_filter(arr[0]),
      rightFilters: dco_decode_list_active_filter(arr[1]),
      matchedL: dco_decode_list_point(arr[2]),
      matchedR: dco_decode_list_point(arr[3]),
      residualImbalanceDb: dco_decode_f_32(arr[4]),
    );
  }

  @protected
  CrossfeedCoefficients dco_decode_crossfeed_coefficients(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return CrossfeedCoefficients(
      a0Lo: dco_decode_f_64(arr[0]),
      b1Lo: dco_decode_f_64(arr[1]),
      a0Hi: dco_decode_f_64(arr[2]),
      a1Hi: dco_decode_f_64(arr[3]),
      b1Hi: dco_decode_f_64(arr[4]),
      gain: dco_decode_f_64(arr[5]),
      fCut: dco_decode_f_64(arr[6]),
      feedDb: dco_decode_f_64(arr[7]),
      sampleRate: dco_decode_f_64(arr[8]),
    );
  }

  @protected
  CrossfeedConfig dco_decode_crossfeed_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return CrossfeedConfig(
      enabled: dco_decode_bool(arr[0]),
      fCut: dco_decode_f_64(arr[1]),
      feedDb: dco_decode_f_64(arr[2]),
      name: dco_decode_String(arr[3]),
    );
  }

  @protected
  CrossfeedPresetMode dco_decode_crossfeed_preset_mode(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return CrossfeedPresetMode.values[raw as int];
  }

  @protected
  DualMeasurementResult dco_decode_dual_measurement_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return DualMeasurementResult(
      isDualChannel: dco_decode_bool(arr[0]),
      rawL: dco_decode_list_point(arr[1]),
      rawR: dco_decode_list_point(arr[2]),
      rawMid: dco_decode_list_point(arr[3]),
      avgImbalanceDb: dco_decode_f_32(arr[4]),
      maxImbalanceDb: dco_decode_f_32(arr[5]),
      maxImbalanceFreq: dco_decode_f_32(arr[6]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FilterType dco_decode_filter_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FilterType.values[raw as int];
  }

  @protected
  HeadphoneModel dco_decode_headphone_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return HeadphoneModel(
      brand: dco_decode_String(arr[0]),
      model: dco_decode_String(arr[1]),
      formFactor: dco_decode_opt_String(arr[2]),
      rig: dco_decode_opt_String(arr[3]),
      filePath: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<ActiveFilter> dco_decode_list_active_filter(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_active_filter).toList();
  }

  @protected
  List<HeadphoneModel> dco_decode_list_headphone_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_headphone_model).toList();
  }

  @protected
  List<Point> dco_decode_list_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_point).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<UserPresetModel> dco_decode_list_user_preset_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_user_preset_model).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  Point dco_decode_point(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Point(x: dco_decode_f_32(arr[0]), y: dco_decode_f_32(arr[1]));
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UserPresetModel dco_decode_user_preset_model(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return UserPresetModel(
      id: dco_decode_i_64(arr[0]),
      name: dco_decode_String(arr[1]),
      createdAt: dco_decode_String(arr[2]),
      filters: dco_decode_list_active_filter(arr[3]),
      preamp: dco_decode_f_32(arr[4]),
      headphoneName: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  ActiveFilter sse_decode_active_filter(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_filterType = sse_decode_filter_type(deserializer);
    var var_freq = sse_decode_f_32(deserializer);
    var var_gain = sse_decode_f_32(deserializer);
    var var_q = sse_decode_f_32(deserializer);
    return ActiveFilter(
      filterType: var_filterType,
      freq: var_freq,
      gain: var_gain,
      q: var_q,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChannelMatchResult sse_decode_channel_match_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_leftFilters = sse_decode_list_active_filter(deserializer);
    var var_rightFilters = sse_decode_list_active_filter(deserializer);
    var var_matchedL = sse_decode_list_point(deserializer);
    var var_matchedR = sse_decode_list_point(deserializer);
    var var_residualImbalanceDb = sse_decode_f_32(deserializer);
    return ChannelMatchResult(
      leftFilters: var_leftFilters,
      rightFilters: var_rightFilters,
      matchedL: var_matchedL,
      matchedR: var_matchedR,
      residualImbalanceDb: var_residualImbalanceDb,
    );
  }

  @protected
  CrossfeedCoefficients sse_decode_crossfeed_coefficients(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_a0Lo = sse_decode_f_64(deserializer);
    var var_b1Lo = sse_decode_f_64(deserializer);
    var var_a0Hi = sse_decode_f_64(deserializer);
    var var_a1Hi = sse_decode_f_64(deserializer);
    var var_b1Hi = sse_decode_f_64(deserializer);
    var var_gain = sse_decode_f_64(deserializer);
    var var_fCut = sse_decode_f_64(deserializer);
    var var_feedDb = sse_decode_f_64(deserializer);
    var var_sampleRate = sse_decode_f_64(deserializer);
    return CrossfeedCoefficients(
      a0Lo: var_a0Lo,
      b1Lo: var_b1Lo,
      a0Hi: var_a0Hi,
      a1Hi: var_a1Hi,
      b1Hi: var_b1Hi,
      gain: var_gain,
      fCut: var_fCut,
      feedDb: var_feedDb,
      sampleRate: var_sampleRate,
    );
  }

  @protected
  CrossfeedConfig sse_decode_crossfeed_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_enabled = sse_decode_bool(deserializer);
    var var_fCut = sse_decode_f_64(deserializer);
    var var_feedDb = sse_decode_f_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    return CrossfeedConfig(
      enabled: var_enabled,
      fCut: var_fCut,
      feedDb: var_feedDb,
      name: var_name,
    );
  }

  @protected
  CrossfeedPresetMode sse_decode_crossfeed_preset_mode(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return CrossfeedPresetMode.values[inner];
  }

  @protected
  DualMeasurementResult sse_decode_dual_measurement_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isDualChannel = sse_decode_bool(deserializer);
    var var_rawL = sse_decode_list_point(deserializer);
    var var_rawR = sse_decode_list_point(deserializer);
    var var_rawMid = sse_decode_list_point(deserializer);
    var var_avgImbalanceDb = sse_decode_f_32(deserializer);
    var var_maxImbalanceDb = sse_decode_f_32(deserializer);
    var var_maxImbalanceFreq = sse_decode_f_32(deserializer);
    return DualMeasurementResult(
      isDualChannel: var_isDualChannel,
      rawL: var_rawL,
      rawR: var_rawR,
      rawMid: var_rawMid,
      avgImbalanceDb: var_avgImbalanceDb,
      maxImbalanceDb: var_maxImbalanceDb,
      maxImbalanceFreq: var_maxImbalanceFreq,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FilterType sse_decode_filter_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FilterType.values[inner];
  }

  @protected
  HeadphoneModel sse_decode_headphone_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_brand = sse_decode_String(deserializer);
    var var_model = sse_decode_String(deserializer);
    var var_formFactor = sse_decode_opt_String(deserializer);
    var var_rig = sse_decode_opt_String(deserializer);
    var var_filePath = sse_decode_opt_String(deserializer);
    return HeadphoneModel(
      brand: var_brand,
      model: var_model,
      formFactor: var_formFactor,
      rig: var_rig,
      filePath: var_filePath,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<ActiveFilter> sse_decode_list_active_filter(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ActiveFilter>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_active_filter(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeadphoneModel> sse_decode_list_headphone_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeadphoneModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_headphone_model(deserializer));
    }
    return ans_;
  }

  @protected
  List<Point> sse_decode_list_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Point>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_point(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<UserPresetModel> sse_decode_list_user_preset_model(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <UserPresetModel>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_user_preset_model(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Point sse_decode_point(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_32(deserializer);
    var var_y = sse_decode_f_32(deserializer);
    return Point(x: var_x, y: var_y);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UserPresetModel sse_decode_user_preset_model(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_i_64(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_String(deserializer);
    var var_filters = sse_decode_list_active_filter(deserializer);
    var var_preamp = sse_decode_f_32(deserializer);
    var var_headphoneName = sse_decode_opt_String(deserializer);
    return UserPresetModel(
      id: var_id,
      name: var_name,
      createdAt: var_createdAt,
      filters: var_filters,
      preamp: var_preamp,
      headphoneName: var_headphoneName,
    );
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_active_filter(ActiveFilter self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_filter_type(self.filterType, serializer);
    sse_encode_f_32(self.freq, serializer);
    sse_encode_f_32(self.gain, serializer);
    sse_encode_f_32(self.q, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_channel_match_result(
    ChannelMatchResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_active_filter(self.leftFilters, serializer);
    sse_encode_list_active_filter(self.rightFilters, serializer);
    sse_encode_list_point(self.matchedL, serializer);
    sse_encode_list_point(self.matchedR, serializer);
    sse_encode_f_32(self.residualImbalanceDb, serializer);
  }

  @protected
  void sse_encode_crossfeed_coefficients(
    CrossfeedCoefficients self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.a0Lo, serializer);
    sse_encode_f_64(self.b1Lo, serializer);
    sse_encode_f_64(self.a0Hi, serializer);
    sse_encode_f_64(self.a1Hi, serializer);
    sse_encode_f_64(self.b1Hi, serializer);
    sse_encode_f_64(self.gain, serializer);
    sse_encode_f_64(self.fCut, serializer);
    sse_encode_f_64(self.feedDb, serializer);
    sse_encode_f_64(self.sampleRate, serializer);
  }

  @protected
  void sse_encode_crossfeed_config(
    CrossfeedConfig self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.enabled, serializer);
    sse_encode_f_64(self.fCut, serializer);
    sse_encode_f_64(self.feedDb, serializer);
    sse_encode_String(self.name, serializer);
  }

  @protected
  void sse_encode_crossfeed_preset_mode(
    CrossfeedPresetMode self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dual_measurement_result(
    DualMeasurementResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isDualChannel, serializer);
    sse_encode_list_point(self.rawL, serializer);
    sse_encode_list_point(self.rawR, serializer);
    sse_encode_list_point(self.rawMid, serializer);
    sse_encode_f_32(self.avgImbalanceDb, serializer);
    sse_encode_f_32(self.maxImbalanceDb, serializer);
    sse_encode_f_32(self.maxImbalanceFreq, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_filter_type(FilterType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_headphone_model(
    HeadphoneModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.brand, serializer);
    sse_encode_String(self.model, serializer);
    sse_encode_opt_String(self.formFactor, serializer);
    sse_encode_opt_String(self.rig, serializer);
    sse_encode_opt_String(self.filePath, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_active_filter(
    List<ActiveFilter> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_active_filter(item, serializer);
    }
  }

  @protected
  void sse_encode_list_headphone_model(
    List<HeadphoneModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_headphone_model(item, serializer);
    }
  }

  @protected
  void sse_encode_list_point(List<Point> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_point(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_user_preset_model(
    List<UserPresetModel> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_user_preset_model(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_point(Point self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_32(self.x, serializer);
    sse_encode_f_32(self.y, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_user_preset_model(
    UserPresetModel self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.createdAt, serializer);
    sse_encode_list_active_filter(self.filters, serializer);
    sse_encode_f_32(self.preamp, serializer);
    sse_encode_opt_String(self.headphoneName, serializer);
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
