// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// BS2B crossfeed filter coefficients.
class CrossfeedCoefficients {
  final double a0Lo;
  final double b1Lo;
  final double a0Hi;
  final double a1Hi;
  final double b1Hi;
  final double gain;
  final double fCut;
  final double feedDb;
  final double sampleRate;

  const CrossfeedCoefficients({
    required this.a0Lo,
    required this.b1Lo,
    required this.a0Hi,
    required this.a1Hi,
    required this.b1Hi,
    required this.gain,
    required this.fCut,
    required this.feedDb,
    required this.sampleRate,
  });

  @override
  int get hashCode =>
      a0Lo.hashCode ^
      b1Lo.hashCode ^
      a0Hi.hashCode ^
      a1Hi.hashCode ^
      b1Hi.hashCode ^
      gain.hashCode ^
      fCut.hashCode ^
      feedDb.hashCode ^
      sampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CrossfeedCoefficients &&
          runtimeType == other.runtimeType &&
          a0Lo == other.a0Lo &&
          b1Lo == other.b1Lo &&
          a0Hi == other.a0Hi &&
          a1Hi == other.a1Hi &&
          b1Hi == other.b1Hi &&
          gain == other.gain &&
          fCut == other.fCut &&
          feedDb == other.feedDb &&
          sampleRate == other.sampleRate;
}
